### ISSUE TITLE
Vulnerable dependencies

### ISSUE THREAD

**Issue by JonRowe** [DatabaseCleaner/database_cleaner-couch_potato#1]
This repo is unmaintained but has security vulnerabilities in its dependencies, can we either archive this repo (and update the readme with instructions for how to contact to take up maintainer ship) or turn off the security updates (or fix them?)

**Comment by etagwerker** [comment]
@JonRowe Thanks for bringing this up! I'm going to archive this repo.

If anyone is interested in maintaining this adapter, please open an issue here: https://github.com/DatabaseCleaner/database_cleaner/issues
